---
  - name: Install Additional Packages For ISCSI Server
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - targetcli-fb
    when: ansible_hostname == 'iscsi'
  
  - name: Setup targetcli
    shell: |
         targetcli /backstores/block create disk01 /dev/vdb
         targetcli /iscsi create iqn.2026-02.ru.otus:storage-iscsi.target00
         targetcli /iscsi/iqn.2026-02.ru.otus:storage-iscsi.target00/tpg1/portals create 0.0.0.0
         targetcli /iscsi/iqn.2026-02.ru.otus:storage-iscsi.target00/tpg1/luns create /backstores/block/disk01 lun=1
         targetcli /iscsi/iqn.2026-02.ru.otus:storage-iscsi.target00/tpg1 set attribute authentication=0
         targetcli /iscsi/iqn.2026-02.ru.otus:storage-iscsi.target00/tpg1 set auth userid=otus
         targetcli /iscsi/iqn.2026-02.ru.otus:storage-iscsi.target00/tpg1 set auth password=otus
         targetcli /iscsi/iqn.2026-02.ru.otus:storage-iscsi.target00/tpg1/acls create iqn.2026-02.ru.otus:pcs-1
         targetcli /iscsi/iqn.2026-02.ru.otus:storage-iscsi.target00/tpg1/acls create iqn.2026-02.ru.otus:pcs-2
         targetcli /iscsi/iqn.2026-02.ru.otus:storage-iscsi.target00/tpg1/acls create iqn.2026-02.ru.otus:pcs-3
         targetcli saveconfig
    when: ansible_hostname == 'iscsi'

  - name: Install Additional Packages For Pacemaker Servers
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - multipath-tools
      - open-iscsi
    when: ansible_hostname is match("pcs-*")

  - name: Set new InitiatorName in config file
    lineinfile:
       path: /etc/iscsi/initiatorname.iscsi
       regexp: '^InitiatorName='
       line: "InitiatorName=iqn.2026-02.ru.otus:{{ ansible_hostname }}"
       state: present
    when: ansible_hostname is match("pcs-*")
    notify:
      - Restart iscsid
    
    

  - name: "Enable and Start ISCSI Service"
    systemd:
      name: "{{ item }}"
      state: restarted
      enabled: true
    with_items:
      - iscsid
    when: ansible_hostname is match("pcs-*")

  - name: Connect iscsi in PCS Servers
    shell: |
         iscsiadm -m discovery -t st -p 10.180.2.204
         iscsiadm -m discovery -t st -p 10.180.3.204
         iscsiadm -m node -l 
    when: ansible_hostname is match("pcs-*")

  - name: Setup multipath in PCS Servers
    shell: |
        mpathconf --enable --with_multipathd y
    when: ansible_hostname is match("pcs-*")

  - name: Copy multipath conf file
    ansible.builtin.copy:
      src: ./roles/iscsi/files/multipath.conf
      dest: /etc/multipath.conf
      follow: yes
    when: ansible_hostname is match("pcs-*")
  #  notify:
  #    - Restart multipathd

  - name: Setup multipath in PCS Servers
    shell: |
        wwid=`/usr/lib/udev/scsi_id --whitelisted --replace-whitespace --device=/dev/sda`
        sed -i "s/wwid*.*/wwid $wwid/g" /etc/multipath.conf
    when: ansible_hostname is match("pcs-*")

  - name: "Enable and Start Multipathd Service"
    systemd:
      name: "{{ item }}"
      state: restarted
      enabled: true
    with_items:
      - multipathd
    when: ansible_hostname is match("pcs-*")
# tasks file for iscsi

