---
- name: Restart multipathd
  systemd:
    name: multipathd
    state: restarted
    enabled: true

- name: Restart iscsid
  systemd:
    name: iscsid
    state: restarted
    enabled: true

# handlers file for iscsi
