---
# handlers file for docker
- name: enable docker
  service:
    name: docker
    enabled: yes
  listen: start docker

#Note that reloaded will start the service if it is not already started
- name: reload docker
  service:
    name: docker
    state: started
  listen: start docker