#cloud-config
ssh_pwauth: no
users:
  - name: admind
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDcjwLPdsZz3buj3YioPSEPUqmiSr7nyNL+3hm8+jGrh maksim@DESKTOP-DHVBQLG"
