---
# tasks file for backend
- name: create dirs
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - /opt/webdebugger

- name: copy backdrop compose file
  template:
    src: backdrop.yml
    dest: "/var/webdebugger/docker-compose.yaml"

- name: Run docker-compose file
  community.docker.docker_compose_v2:
    project_src: "/opt/webdebugger"
    state: present

